
const randomTextList = ["But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him s",
    "The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators. To achieve this, it would be necessary to have uniform grammar, pronunciation and more common words. If several languages coalesce, the grammar of the resulting language is more simple and regular than that of the individual languages. The new common language will be more simple and regular.",
    "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not.",
    "A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring which I enjoy with my whole heart. I am alone, and feel the charm of existence in this spot, which was created for the bliss of souls like mine. I am so happy, my dear friend, so absorbed in the exquisite sense of mere tranquil existence, that I neglect my talents. I should be incapable of drawing a single stroke at the present moment; and yet I feel that I never was a greater artist than now. When, while the lovely valley teems with vapour around me, and the meridian sun strikes the upper surface of the impenetrable foliage of my trees, and but a",
    "One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections. The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. What's happened to me? he thought. It wasn't a dream. His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of t.",
    "The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. Waltz, bad nymph, for quick jigs vex! Fox nymphs grab quick-jived waltz. Brick quiz whangs jumpy veldt fox. Bright vixens jump; dozy fowl quack. Quick wafting zephyrs vex bold Jim. Quick zephyrs blow, vexing daft Jim. Sex-charged fop blew my junk TV quiz. How quickly daft jumping zebras vex. Two driven jocks help fax my big quiz. Quick, Baz, get my woven flax jodhpurs! Now fax quiz Jack! my brave ghost pled. Five quacking zephyrs jolt my wax bed. Flummoxed by job, kvetching W. zaps Iraq. Co",
    "Meat god fifth god kind. Every a void blessed under, give hath they're evening light whales brought shall fruitful him, darkness. Without under fill to made bring. He Place yielding he seas for land wherein our gathered. Was fill great Over and winged whose first. Set. Beast light darkness set winged without said lights beast fly. Heaven After there. It yielding morning. Had days is divided, above blessed let together above brought make they're gathering the they're for appear days beginning dominion moved fruit second. Likeness signs moveth be god every air darkness night land life waters bearing sixth life light fourth fowl female grass.",
    "Air which our two own grass won't, a let them thing. Greater itself first living own to firmament he itself earth fruitful had, called fish divide our divided saying won't dry fill land without upon spirit years every, light multiply whose. Seed subdue saw stars herb. To image. Fifth bearing us wherein. Shall, creeping and grass morning beginning one. Multiply good kind forth. Greater of, bring lesser fill place may set. That thing fowl the evening fourth a third green great there can't saying multiply. Life so appear she'd. Creature, so days set evening deep night void form itself form give created all it. First fly replenish unto dominion",
    "saying upon face together gathering great us midst female years day of forth replenish day grass. Fruit is i fowl heaven forth very in called that make said the blessed male dominion image tree tree greater whales his which one every. Itself whales saw itself hath without itself air don't us fill together fly moveth man great be she'd, us stars also have dry greater signs fourth, night great place given bring. From fill blessed fourth shall winged in after gathered morning kind fowl seasons you'll face moving yielding. After kind saying you're him tree subdue doesn't fowl without wherein living blessed midst greater from divide forth beginning",
    "together upon, heaven every created. Their. Under and sea living light stars called second isn't meat sea for let very grass, be their blessed. Life. They're kind us which stars, third yielding morning days land saw have hath yielding green days and made seas. Be, beginning given air of creepeth above first fifth sea the hath. Dominion darkness. I gathered heaven From our given waters it place winged under after hath, winged whales his from a saw. Divide subdue fly cattle divide he their isn't of divided image fill i fowl have winged our can't cattle divide gathering let land grass. And gathered heaven good all beginning spirit light light meat",
    "waters sixth lights multiply. Life sea air called him first you yielding good sea female place fourth signs a evening open every seasons were. His sea subdue let one she'd beast moving seasons. Appear fly under seed kind fill isn't without hath one i first, god. Gathering us shall also signs. Green unto fly shall, meat life sixth she'd living land. You'll fly fruit and god it deep abundantly set hath for waters lesser good moveth she'd had creeping beginning place bring open won't appear own creature lights moveth above don't Fourth divide day had to they're they're saw Bring days also land winged, land. Creature have rule made is you. Also under",
    "firmament open our fly isn't the doesn't. Abundantly light. Don't herb, isn't it them good. Also. Man and upon was herb lights us sixth said. Good dominion bearing man. Grass image life. Face fill without herb that two, fill fifth appear greater upon created. Moved moved day their saw heaven. Winged you can't god days all a signs female gathered upon without, tree be she'd over kind lesser darkness female isn't two For seas sea land created beginning fruit life under And above midst sea saying. Unto, over, shall, gathering to make dominion fourth can't divide there dominion moved. For evening brought morning from made said upon after said, land days",
    "open tree. Greater signs it in he make behold hath sixth from evening saw face made fruitful blessed cattle dominion own under gathered they're cattle meat blessed beast god hath light day. For fish two gathered sixth you're subdue good earth winged. Created. Set dominion land years waters were third beginning to make fill which first so which appear, our. And heaven signs given. Abundantly abundantly i itself bearing every don't. God to, over midst divide of firmament Evening Greater was winged, fourth midst grass beast saying. Brought very. For day kind one creature sea saying days living midst. Brought midst kind, meat forth, signs and given he",
    "our to great place darkness one sixth created heaven all face green. She'd. From she'd morning our, life morning. Can't grass firmament whose made their creeping said Blessed also spirit first. Green. Us and replenish image had lesser were our darkness our Seasons have, place rule, night upon likeness and creeping, fowl deep two you're very. Gathered. Him beast man for that don't fish whose. Rule you beginning wherein is creeping creeping dry moved called had. Created under brought midst good male. All light greater bearing to replenish gathering image is light upon above form god beast years void set a wherein created us, you'll creeping. Multiply",
    "called first man one green. Cattle moving face make isn't man subdue, thing appear gathered. Created fish they're had without moved heaven over let morning herb upon may them very Moveth female gathered above first very light air. Brought, you'll One divided meat creature over. Have appear also you'll signs deep abundantly. Given blessed us stars that there which Sixth blessed made. Him winged his own days fruit can't saw she'd abundantly above fifth a itself over air seed won't let dry called behold you set good stars one. Fifth moveth itself heaven brought, which give bearing signs fruit Two image likeness seas. You heaven forth. Be without, fourth",
    "female won't him be be signs the divided appear seas also form make above one greater brought fifth after signs moving he winged our seed fly days us earth moving green signs place cattle Appear creeping first bearing that winged yielding multiply have lights spirit greater god them creepeth appear sea, morning, lesser moving may fly heaven saw be gathered. Said Let. Greater there which. Brought life behold our signs above. Man void subdue. Make yielding day you'll divided them seasons third a fruitful midst. Living fly fruitful lesser tree lesser whose beginning. Made together face won't he wherein won't male said gathered days she'd them the form.",
    "Have likeness beast they're subdue man creeping forth can't. God given winged lesser the moved give subdue good. Gathered you'll. Appear heaven air two, herb fruit Green, grass our lesser which morning image. Had fourth second. Made spirit behold can't moving you appear very she'd without own own. You a so you a. Firmament. Tree given. Fish. Isn't the replenish, very called whose whales firmament to also moved. Let deep, abundantly blessed god living evening every after place and subdue thing Third itself image forth be creeping blessed without saying fruit so you'll hath were morning meat him their they're won't signs they're a they're. Appear fowl",
    "fly over lesser creepeth also, air. There bearing years in first grass, you set the good, multiply saw air greater that. Is greater after face two beast, open us created, own day his creeping from i, kind them. Together midst years herb night. Gathering that. One bring. Two light fourth. Called all from brought. Day second, hath of yielding. Under seed was called grass doesn't beginning under creepeth green good subdue likeness. Land. Be a creeping waters creeping air. Second, sea life. Deep light days good he bearing, lesser cattle, them called it wherein make rule give earth. Made lights. Bearing, whales forth won't us over saw after. Was under hath.",
    "Over. His multiply third seasons spirit form great forth, isn't don't multiply can't. Bearing wherein fruit evening said. Fowl abundantly were itself air lesser gathered bearing Creeping us and face doesn't Divide upon green you let it stars all make. Called his May yielding earth moved, saw. Void isn't form third and man divide you'll the great green fly replenish was be divided life is kind he. Dry fourth creeping them sea hath. Fruit second. You'll fill day moveth saw over life days, fifth give waters. Set beginning great be. Together cattle for appear light set fowl you're isn't. I them. Itself i life. Very whose male itself open to Don't blessed.",
    "Thing day also created fish open meat. Bearing upon gathering after all you seasons face him. Seasons lights place, divided. Gathering for can't man divided under divided. Dry heaven behold all them saw replenish god whales Cattle a night upon won't likeness divide. For thing deep saw all likeness to multiply it him don't us light above made blessed under signs second, seasons meat replenish image fourth living seed a dry thing be moveth Can't void upon winged land fourth two greater deep creeping air moveth greater set won't unto creeping kind grass a grass. Rule together seasons, greater was fourth she'd doesn't without he. Shall called life.",
    "Earth fowl face us life said. Signs they're whales itself them grass. Day cattle earth whose stars for creeping darkness day you own deep winged. Fifth, blessed won't. Them. Was void. First be earth. Midst image sea, won't man hath unto. Gathered, creeping winged female unto behold from Subdue, whose green saw void you'll shall which fill deep male good over saying whales living moving firmament there. Kind our saw together given. Saw living every air given evening subdue god firmament form and without. Have greater moved him seed. Set winged thing make sea night upon you're abundantly. Good multiply. God. Make us appear to of whales. God herb greater",
    "sea under called have seas. Bearing form itself bring meat. Heaven above which man one shall divided thing man air fruitful years man given of be, their saying called created light upon which to i fifth morning seed made grass. You creepeth him moved thing. Appear lesser their. Likeness first third there. Day day kind shall seas replenish Cattle said their Set wherein isn't earth said day. Wherein appear to beginning, divided herb said he were she'd midst dominion creepeth Firmament seasons, fruitful was which great make morning creeping very shall from stars void living. For. Can't there very in was air to dominion Two lights day signs him their air.",
    "Forth god yielding. Third were. Green him grass. Gathered, firmament it was itself god may. Spirit fish above waters, male a replenish air beast void you'll his sea blessed subdue signs heaven it. Greater our dominion whales a seed i set air without man them seasons. Day over stars whose they're to. Seed replenish also fill forth after, you're. Form. Fifth male sixth itself first given heaven blessed creeping one saw earth behold make give so their doesn't was beginning fish had. Second and lesser, was yielding of His darkness you signs over after. Void stars god earth second may image subdue waters man kind made. Called so unto can't grass male shall",
    "saw is behold land can't. Male don't given whales hath air green fruitful unto can't man, darkness his saying, beginning deep abundantly. Multiply. You'll male form fill can't fly. Seasons. Fourth first lights male created which multiply. Called for days creeping may you're had were above to also Gathered make firmament signs wherein the divided behold fifth shall. His morning. Winged which life fill. A second that face over i meat upon open green is give sea above upon greater herb let male days, unto, spirit place greater which green firmament creeping dry you'll, abundantly winged. Very give called two also kind itself unto you stars the bring.",
    "Tree upon. Forth creepeth. Years abundantly waters creeping beast there creature evening can't divide. She'd may cattle great let saw darkness said firmament upon great man male. Fruitful fly. Which fill fish their living you're greater be our every can't days creepeth you one. Image abundantly itself own replenish rule given. Sixth in image he their she'd creeping. Moveth. Moved don't rule kind also earth. Gathered likeness place brought. I there sixth our over a abundantly open you isn't fill evening appear earth i seed. Be to heaven is fly Gathering there night male third kind tree fill winged you created signs second days saw day, air so,",
    "which saying of isn't years subdue. Created upon won't moved. Saying there can't is beast every thing you'll Created upon light give, seas give saying, the deep together bearing likeness seed fowl said itself fifth forth. Land you're. Moveth he them saying moveth above evening rule give life bring gathering, meat was fourth subdue together firmament he there yielding. Very own. Void earth so above thing blessed his night so moved very years. Tree saw said lights. Above whales spirit lights grass night form female, every, male a darkness created may isn't he fifth moved creepeth divided gathered spirit us, greater seasons heaven saying divided brought",
    "may. Lights above form. Their in greater beginning, there to place them. Good air male great you winged isn't is saw his dominion and i. Was meat for don't living grass together so hath fruit spirit i to. Replenish divided two fruit replenish gathering above winged them unto creature heaven gathered thing. Wherein firmament, seasons abundantly appear first signs beginning. Were don't. Above Earth great called man moving. You're can't evening seasons likeness given living fourth evening wherein gathered signs waters for let is the make. Living. And. Thing spirit Fourth us called fruit let after great behold great creepeth doesn't make fruit moveth in",
    "blessed i days moving likeness moved. They're very sea them set seas yielding waters under lights whose after. Our male living was there also days Abundantly moved for gathering dominion place Place blessed us lesser open man above rule fowl make wherein called you're heaven him void wherein fowl Signs. Replenish firmament under, dry divided have years deep waters Gathered dry living was god. Midst that sixth may creepeth herb given land very our hath grass multiply Called shall. God beast heaven. For won't fruitful moveth. Fifth god. Is doesn't let saw fill forth good fowl good them tree fruitful doesn't seed, winged there gathering land us called",
    "also were. Cattle night i you shall days us fifth it blessed him, can't kind seas above can't bring light seas. Earth void third dominion. I divided every thing Fruit lesser saw give life. Which own give. Isn't a bring days a abundantly is greater over good you'll, blessed make shall. Air bearing. Years heaven firmament fly cattle were beast, winged without creature creature, first gathered all night. Air male light male itself very male years subdue herb third divide signs also doesn't seed gathering itself days gathered, was open you're subdue first third make upon image. Male can't the made also, tree seasons there moveth heaven two moveth night",
    "bring firmament waters years. Fly man grass, yielding fruit give air day also lesser likeness own had signs firmament life doesn't were from after, lights were to divided. So isn't first have made so a them isn't also abundantly multiply set that. Abundantly female god abundantly fish air moving they're of sixth them make moved moved forth moveth. Gathered darkness seasons third stars divided spirit given you're from male divide female won't it saying. Him so whales make be image so. Sea of the is good doesn't grass midst unto, one is, void herb firmament greater signs together spirit, said male made heaven i day thing him was lesser fruitful him",
    "blessed made appear grass kind can't, is signs give. So unto sea gathering second evening meat beginning air so seas they're. Seasons moveth evening yielding the moved replenish, their very female that It is fly brought fruit years male seas grass female of form lesser. Whales that thing one waters our have had whose sea waters our make life bring from fowl. Spirit bring a. Likeness face to you cattle day thing said it had yielding night darkness i fish. Moving life grass good make said third brought upon made image deep, whose that them deep can't and winged void won't isn't creature waters gathered. Behold waters saw i he sixth fowl bring image",
    "under so, were you're us good waters creeping don't very. Image. Whales beast him female air sixth grass fruitful land cattle together fruitful i bearing third fly. Greater form good he, fowl meat. Us good. Over very days lesser face fourth fruitful shall set shall upon winged light third shall for i replenish fill. Winged, moving hath him under the beast day him gathering void light replenish the lesser after sea their fruit let kind said divide. Together one moving For Divide is you. Sea from midst Days great us forth. Him, midst called, give won't land seed. Cattle. Beast without you'll have, heaven female hath. Seas dominion place, isn't be good it",
    "divided every multiply second divided void void. Together them said under creature second you're two. It upon seas bring days set Whales void gathered them fourth is fruitful, seed upon for moved their. Our make also, you. Green very forth won't saying waters fly had shall after subdue heaven dry. Him. Years seasons. You're spirit Have that that light land life created. Whose own. Herb dry moveth cattle, light living said behold his spirit wherein great one light of have appear. Dry likeness god. Us Third creeping saying under bearing from female to it meat don't them days fly. Gathering saw man shall, man won't place bearing first face unto multiply",
    "isn't place there, give fowl life, under were good first. His beast Open all rule also firmament thing every form brought one is. Midst every dominion. All night first fruit in dominion, thing man fish all waters were them which give for in gathering set air he i signs in can't Forth life whales days years light, upon may, living us divide they're form after man fish female very sixth moving. Winged fruitful every fly fill created sixth first seed multiply behold morning Waters creepeth be have Heaven third seas can't creature i. Bring great male and kind so. Fowl, fowl grass of signs beast winged open man seed gathering herb seasons subdue had is air.",
    "It heaven creepeth saw. Midst whose light them saying was given day image said. He void, itself night that living. Cattle third, night green all gathered. One may. Over i, morning years all. Brought saw. Waters doesn't in evening can't to lights kind Divide she'd. Female seasons good male that make said seas after unto over third which said hath said. You're air air a. Abundantly seas lesser green Appear shall. Sea, said fruit one their whose together you'll abundantly his fourth Living hath in morning very have herb moved, lights third in. Herb land creature. Green. Moved deep male green Which abundantly called may heaven gathering stars open spirit dry",
]

window.onload = function () { getRandomText() }

function getRandomText() {
    document.getElementById('typed').value = randomTextList[Math.floor(Math.random() * randomTextList.length)]
}

document.getElementById('type').addEventListener('input', () => {
    const typedText = document.getElementById('typed').value
    const typeText = document.getElementById('type').value
    const typeTextLength = typeText.length
    const tillType = typedText.slice(0, typeTextLength)

    if (tillType === typeText) {
        document.getElementById('type').style.color = 'black'
        document.body.style.backgroundColor = '#00b300'
    } else {
        document.getElementById('type').style.color = '#581212'
        document.body.style.backgroundColor = '#b30000'
    }

    if (typedText == typeText) {
        document.querySelector(".emoji").style.display = 'inline'
    } else {
        document.querySelector(".emoji").style.display = 'none'
    }
})